deploy_environment: &deploy_environment
  docker:
    - image: circleci/node:10

version: 2
jobs:
  build:
    <<: *deploy_environment
    steps:
      - checkout
      - run: 
          name: Install npm deps
          command: npm install
      # npm build runs lerna run build. lerna will potentially build unneeded assets.
      # if build gets slow in future we should investigate removing unneeded asset builds from lerna
      - run:
          name: Build bundle
          command: |
            set -e
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    <<: *deploy_environment
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  deploy:
    <<: *deploy_environment
    environment:
      S3_BUCKET_PATH: "s3://knowledgebase.nearform.com"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install awscli
          command: |
            sudo apt-get install python-pip python
            sudo pip install awscli
      - run:
          name: Deploy bundle to S3
          command: aws s3 sync packages/app/public ${S3_BUCKET_PATH} --delete --cache-control max-age=0,no-cache,no-store,must-revalidate

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
