version: '3.6'
services:
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./:/local_dir #mount current dir so you can access the pg_dump file
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orion
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/orion
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      ## not needed for local dev, but be aware the api calls wont be authenticated
      #HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
